INSERT INTO category(description) VALUES ('American');
INSERT INTO category(description) VALUES ('Italian');
insert into category(description) VALUES ('Mexican');
insert into category(description) VALUES ('Fast Food');
insert into unit_of_measure(description) VALUES ('Each');
insert into unit_of_measure(description) VALUES ('Teaspoon');
insert into unit_of_measure(description) VALUES ('Tablespoon');
insert into unit_of_measure(description) VALUES ('Cup');
insert into unit_of_measure(description) VALUES ('Pinch');
insert into unit_of_measure(description) VALUES ('Dash');
insert into unit_of_measure(description) VALUES ('Ounce');
insert into unit_of_measure(description) VALUES ('Pint');
